### ISSUE TITLE
预览时,不能取消已选的图片?求大神修复下,万分感激!

### ISSUE THREAD

**Issue by wangzhilongh** [johnil/JFImagePickerController#3]
大神,您好!
预览时,不能取消已选的图片?求大神修复下,万分感激!

**Comment by bawn** [comment]
同样的问题，预览时，取消选择的图片 picker.assets 的数量原来的

**Comment by Lynnll** [comment]
问题同上，作者是不是不维护了已经？

**Comment by DaverZhou** [comment]
问题同上，今天调用的时候直接闪退。。。求解决

**Comment by Lynnll** [comment]
作者都不维护了，推荐大家用更好用的库 TZImagePickerController
